[package]

name = "box2d"
version = "0.2.3"
authors = ["Thomas Koehler <basta.t.k+git@gmail.com>"]

description = "Rust binding for Box2D"
documentation = "https://bastacyclop.github.io/rust_box2d/box2d/"
repository = "https://github.com/Bastacyclop/rust_box2d.git"
readme = "README.md"
keywords = ["physics", "bindings", "box2d"]
license = "zlib"

build = "build_frontend.rs"

[lib]
name = "box2d"

[features]
default = ["nalgebra", "cgmath"]

[build-dependencies]
gcc = "*"

[dependencies]
libc = "*"
vec_map = "*"
bitflags = "*"

[dependencies.nalgebra]
version = "*"
optional = true

[dependencies.cgmath]
version = "*"
optional = true
